source 'https://rubygems.org'

gem 'rails'
gem 'sqlite3'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'redis'
gem 'sidekiq'
gem 'sdoc', group: :doc
gem 'slim'
gem 'bootstrap-sass'
gem 'devise'
gem 'bson_ext'
gem 'devise-bootstrap-views'
gem 'grape'
gem 'kaminari'
gem 'simple_form'
gem 'redcarpet'
gem 'cancancan'
gem 'activemodel-serializers-xml'
gem 'draper'
gem 'puma'
gem 'gon'
gem 'doorkeeper'
gem 'doorkeeper-i18n'
gem 'china_sms', :git => 'https://github.com/xzgyb/china_sms.git'
gem 'carrierwave'
gem 'versionomy'
gem 'grape-entity'
gem 'nested_form_fields'
gem 'mini_magick'
gem 'nokogiri'
gem 'carrierwave-video'
gem 'carrierwave-video-thumbnailer'
gem 'pg'
gem 'figaro'
gem 'savon'
gem 'byebug'

group :development, :test do
  gem "awesome_print", require:"ap"
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
  gem 'better_errors'
  gem 'factory_bot_rails'
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-alias'
  gem 'pry-rails'
end

group :development do
  gem 'web-console'
  gem 'mina'
  gem 'mina-puma'
  gem 'guard'
  gem 'guard-minitest'
  gem 'guard-ctags-bundler'
  gem 'mongo'
  gem 'bulk_insert'
end

group :test do
  gem 'mocha'
  gem 'database_cleaner'
  gem 'minitest-hooks'
end
