source 'https://rubygems.org'

gem 'rails', '>= 5.0.0.beta3', '< 5.1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks', :git => 'https://github.com/turbolinks/turbolinks-classic.git'
gem 'jbuilder', '~> 2.0'
gem 'redis', '~> 3.0'
gem 'sidekiq'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'slim'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'devise', '~> 4.0.0.rc1'
gem 'bson_ext'
gem 'devise-bootstrap-views'
gem 'grape'
gem 'kaminari'
gem 'simple_form'
gem 'redcarpet'
gem 'cancancan'
gem 'activemodel-serializers-xml'
gem 'draper', :git => 'https://github.com/xzgyb/draper.git'
gem 'puma'
gem 'gon'
gem 'doorkeeper', '4.0.0.rc2'
gem 'china_sms', :git => 'https://github.com/xzgyb/china_sms.git'
gem 'carrierwave'
gem 'versionomy'
gem 'grape-entity'
gem 'nested_form_fields'
gem 'mini_magick'
gem 'nokogiri'
gem 'carrierwave-video'
gem 'carrierwave-video-thumbnailer'
gem 'pg'
gem 'figaro'
gem 'savon'

group :development, :test do
  gem "awesome_print", require:"ap"
  gem 'byebug'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'better_errors'
  gem 'factory_girl_rails'
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-alias'
  gem 'pry-rails'
end

group :development do
  gem 'web-console', '~> 3.0'
  gem 'mina'
  gem 'mina-puma', :git => 'https://github.com/xzgyb/mina-puma.git', :require => false
  gem 'guard'
  gem 'guard-minitest'
  gem 'guard-ctags-bundler'
  gem 'mongo'
  gem 'bulk_insert'
end

group :test do
  gem 'mocha'
  gem 'database_cleaner', :git => 'https://github.com/DatabaseCleaner/database_cleaner.git'
  gem 'minitest-hooks'
end
