source 'http://ruby.taobao.org'

gem 'rails', '4.2.3'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'slim'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'devise'
gem 'mongoid', '~>4.0.0'
gem 'bson_ext'
gem 'devise-bootstrap-views'
gem 'grape'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'will_paginate_mongoid'
gem 'will-paginate-i18n'
gem 'simple_form'
gem 'redcarpet'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'better_errors'
end
